import { createFileRoute, Link } from "@tanstack/react-router";
import { AppLayout } from "@/components/AppLayout";
import { useStore } from "@/lib/store";
import { COLORS } from "@/lib/colors";
import { ArrowLeft, Download, FileText } from "lucide-react";
import jsPDF from "jspdf";

export const Route = createFileRoute("/report")({ component: Report });

function Report() {
  const { stats, settings } = useStore();
  const learned = Object.keys(stats.learned).length;
  const acc = stats.attempts ? Math.round((stats.correct / stats.attempts) * 100) : 0;
  const totalScore = Object.values(stats.scores).reduce((a, b) => a + b, 0);
  const week = stats.history.slice(-7);

  const download = () => {
    const doc = new jsPDF({ unit: "pt", format: "a4" });
    const W = doc.internal.pageSize.getWidth();
    doc.setFillColor(255, 95, 162);
    doc.rect(0, 0, W, 90, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(26);
    doc.text("Color Buddy", 40, 50);
    doc.setFontSize(12);
    doc.text("Weekly Learning Report", 40, 72);

    doc.setTextColor(40, 40, 60);
    doc.setFontSize(14);
    doc.text(`Child: ${settings.childName}`, 40, 130);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 40, 152);

    doc.setFontSize(16);
    doc.text("Summary", 40, 195);
    doc.setFontSize(12);
    const rows = [
      ["Colors Learned", `${learned} / ${COLORS.length}`],
      ["Accuracy", `${acc}%`],
      ["Time Spent", `${Math.floor(stats.secondsSpent / 60)} minutes`],
      ["Daily Streak", `${stats.streak} days`],
      ["Total Game Score", `${totalScore}`],
      ["Badges Earned", `${stats.badges.length}`],
    ];
    let y = 220;
    rows.forEach(([k, v]) => {
      doc.setFont("helvetica", "normal");
      doc.text(k, 50, y);
      doc.setFont("helvetica", "bold");
      doc.text(String(v), 320, y);
      y += 22;
    });

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("Game Scores", 40, y + 20);
    doc.setFontSize(12);
    y += 45;
    Object.entries(stats.scores).forEach(([k, v]) => {
      doc.setFont("helvetica", "normal");
      doc.text(k.charAt(0).toUpperCase() + k.slice(1), 50, y);
      doc.setFont("helvetica", "bold");
      doc.text(`★ ${v}`, 320, y);
      y += 20;
    });

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("Weekly Activity", 40, y + 20);
    y += 40;
    const bx = 50, bw = (W - 100) / Math.max(1, week.length || 1);
    const max = Math.max(1, ...week.map((h) => h.learned + h.score));
    week.forEach((h, i) => {
      const ratio = (h.learned + h.score) / max;
      const bh = ratio * 100;
      doc.setFillColor(155, 89, 255);
      doc.rect(bx + i * bw + 4, y + 110 - bh, bw - 8, bh, "F");
      doc.setFontSize(8);
      doc.setTextColor(80, 80, 100);
      doc.text(h.date.slice(5), bx + i * bw + bw / 2 - 10, y + 125);
    });
    y += 150;

    doc.setTextColor(40, 40, 60);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("Badges", 40, y);
    doc.setFontSize(11);
    y += 22;
    if (stats.badges.length === 0) {
      doc.setFont("helvetica", "italic");
      doc.text("Keep learning to earn badges!", 50, y);
    } else {
      stats.badges.forEach((b) => {
        doc.setFont("helvetica", "normal");
        doc.text(`• ${b}`, 50, y);
        y += 18;
      });
    }

    doc.setFontSize(10);
    doc.setTextColor(120, 120, 140);
    doc.text("Generated by Color Buddy", 40, doc.internal.pageSize.getHeight() - 30);

    doc.save(`color-buddy-${settings.childName}-${new Date().toISOString().slice(0, 10)}.pdf`);
  };

  return (
    <AppLayout>
      <div className="px-4 pt-6">
        <div className="flex items-center gap-2">
          <Link to="/" className="rounded-full bg-card p-2 shadow-soft"><ArrowLeft className="h-5 w-5" /></Link>
          <h1 className="font-display text-2xl font-extrabold">Weekly Report</h1>
        </div>

        <div className="mt-4 rounded-3xl bg-gradient-to-br from-fun-purple to-fun-blue p-6 text-white shadow-pop">
          <FileText className="h-10 w-10" />
          <p className="mt-3 text-sm opacity-90">Report for</p>
          <p className="font-display text-3xl font-extrabold">{settings.childName}</p>
          <p className="mt-1 text-xs opacity-80">{new Date().toLocaleDateString()}</p>
        </div>

        <div className="mt-4 space-y-2 rounded-3xl bg-card p-5 shadow-soft">
          <Row k="Colors Learned" v={`${learned} / ${COLORS.length}`} />
          <Row k="Accuracy" v={`${acc}%`} />
          <Row k="Time Spent" v={`${Math.floor(stats.secondsSpent / 60)} min`} />
          <Row k="Streak" v={`${stats.streak} days`} />
          <Row k="Total Game Score" v={`★ ${totalScore}`} />
          <Row k="Badges Earned" v={`${stats.badges.length} / 5`} />
        </div>

        <button
          onClick={download}
          className="mt-5 flex w-full items-center justify-center gap-2 rounded-3xl bg-gradient-to-r from-fun-pink to-fun-purple py-4 text-lg font-extrabold text-white shadow-pop active:scale-95"
        >
          <Download className="h-5 w-5" /> Download PDF
        </button>
      </div>
    </AppLayout>
  );
}

function Row({ k, v }: { k: string; v: string }) {
  return (
    <div className="flex items-center justify-between border-b border-border/40 py-2 last:border-0">
      <span className="text-sm text-muted-foreground">{k}</span>
      <span className="font-bold">{v}</span>
    </div>
  );
}
