/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ReportRouteImport } from './routes/report'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as GamesRouteImport } from './routes/games'
import { Route as CameraRouteImport } from './routes/camera'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as GamesSpeedRouteImport } from './routes/games.speed'
import { Route as GamesMemoryRouteImport } from './routes/games.memory'
import { Route as GamesMatchRouteImport } from './routes/games.match'
import { Route as GamesFindRouteImport } from './routes/games.find'

const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraRoute = CameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesRoute,
} as any)
const GamesSpeedRoute = GamesSpeedRouteImport.update({
  id: '/speed',
  path: '/speed',
  getParentRoute: () => GamesRoute,
} as any)
const GamesMemoryRoute = GamesMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => GamesRoute,
} as any)
const GamesMatchRoute = GamesMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => GamesRoute,
} as any)
const GamesFindRoute = GamesFindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => GamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/camera': typeof CameraRoute
  '/games': typeof GamesRouteWithChildren
  '/learn': typeof LearnRoute
  '/onboarding': typeof OnboardingRoute
  '/report': typeof ReportRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tracker': typeof TrackerRoute
  '/games/find': typeof GamesFindRoute
  '/games/match': typeof GamesMatchRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/speed': typeof GamesSpeedRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/camera': typeof CameraRoute
  '/learn': typeof LearnRoute
  '/onboarding': typeof OnboardingRoute
  '/report': typeof ReportRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tracker': typeof TrackerRoute
  '/games/find': typeof GamesFindRoute
  '/games/match': typeof GamesMatchRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/speed': typeof GamesSpeedRoute
  '/games': typeof GamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/camera': typeof CameraRoute
  '/games': typeof GamesRouteWithChildren
  '/learn': typeof LearnRoute
  '/onboarding': typeof OnboardingRoute
  '/report': typeof ReportRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tracker': typeof TrackerRoute
  '/games/find': typeof GamesFindRoute
  '/games/match': typeof GamesMatchRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/speed': typeof GamesSpeedRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/camera'
    | '/games'
    | '/learn'
    | '/onboarding'
    | '/report'
    | '/rewards'
    | '/settings'
    | '/sitemap.xml'
    | '/tracker'
    | '/games/find'
    | '/games/match'
    | '/games/memory'
    | '/games/speed'
    | '/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/camera'
    | '/learn'
    | '/onboarding'
    | '/report'
    | '/rewards'
    | '/settings'
    | '/sitemap.xml'
    | '/tracker'
    | '/games/find'
    | '/games/match'
    | '/games/memory'
    | '/games/speed'
    | '/games'
  id:
    | '__root__'
    | '/'
    | '/camera'
    | '/games'
    | '/learn'
    | '/onboarding'
    | '/report'
    | '/rewards'
    | '/settings'
    | '/sitemap.xml'
    | '/tracker'
    | '/games/find'
    | '/games/match'
    | '/games/memory'
    | '/games/speed'
    | '/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CameraRoute: typeof CameraRoute
  GamesRoute: typeof GamesRouteWithChildren
  LearnRoute: typeof LearnRoute
  OnboardingRoute: typeof OnboardingRoute
  ReportRoute: typeof ReportRoute
  RewardsRoute: typeof RewardsRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackerRoute: typeof TrackerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/speed': {
      id: '/games/speed'
      path: '/speed'
      fullPath: '/games/speed'
      preLoaderRoute: typeof GamesSpeedRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/memory': {
      id: '/games/memory'
      path: '/memory'
      fullPath: '/games/memory'
      preLoaderRoute: typeof GamesMemoryRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/match': {
      id: '/games/match'
      path: '/match'
      fullPath: '/games/match'
      preLoaderRoute: typeof GamesMatchRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/find': {
      id: '/games/find'
      path: '/find'
      fullPath: '/games/find'
      preLoaderRoute: typeof GamesFindRouteImport
      parentRoute: typeof GamesRoute
    }
  }
}

interface GamesRouteChildren {
  GamesFindRoute: typeof GamesFindRoute
  GamesMatchRoute: typeof GamesMatchRoute
  GamesMemoryRoute: typeof GamesMemoryRoute
  GamesSpeedRoute: typeof GamesSpeedRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesFindRoute: GamesFindRoute,
  GamesMatchRoute: GamesMatchRoute,
  GamesMemoryRoute: GamesMemoryRoute,
  GamesSpeedRoute: GamesSpeedRoute,
  GamesIndexRoute: GamesIndexRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CameraRoute: CameraRoute,
  GamesRoute: GamesRouteWithChildren,
  LearnRoute: LearnRoute,
  OnboardingRoute: OnboardingRoute,
  ReportRoute: ReportRoute,
  RewardsRoute: RewardsRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackerRoute: TrackerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
